apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: my-namespace
data:
  fluent.conf: |
	<source>
	  @type forward
	  port 24224
	  bind 0.0.0.0
	</source>

	<match **>
	  @type elasticsearch
	  host https://elk.taskgrids.com
#	  host elasticsearch.my-namespace.svc.cluster.local
#	  port 9200
	  logstash_format true
	  logstash_prefix fluentd
	  logstash_dateformat %Y%m%d
	  include_tag_key true
	  tag_key @log_name
	</match>

